name: Docs CI

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "**.md"
      - ".github/workflows/docs-ci.yaml"

  pull_request:
    paths:
      - "docs/**"
      - "**.md"
      - ".github/workflows/docs-ci.yaml"

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - uses: tj-actions/changed-files@934b2d2c7e653bb8c968afed5a0428617f09aa24 # v45.0.7
        id: changed-files
        with:
          files: |
            docs/**
            **.md
          separator: ","

      - name: lint
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          pnpm exec markdownlint-cli2 ${{ steps.changed-files.outputs.all_changed_files }}

      - name: fmt
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          # markdown-table-formatter requires a space separated list of files
          echo ${{ steps.changed-files.outputs.all_changed_files }} | tr ',' '\n' | pnpm exec markdown-table-formatter --check
